version: "3.7"
services:
  postgres_db:
    image: 'postgres'
    container_name: db_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    networks:
      - playground-network

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
    environment:
      - TRUSTED_NETWORKS=0.0.0.0/0
    restart: always
    networks:
      - playground-network


  springboot_application:
    container_name: spring-boot-demo-app
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - postgres_db
      - maildev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/demo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_SQL_INIT_MODE=always
      - MAIL_HOST=localhost
      - MAIL_PORT=1025
    networks:
      - playground-network

networks:
  playground-network:
    ipam:
      driver: default