version: "3.7"
services:
  app:
    container_name: spring-boot-demo-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

